### ISSUE TITLE
Module doesn't work together with Joycond

### ISSUE THREAD

**Issue by joaorb64** [nicman23/dkms-hid-nintendo#1]
First of all, I want to thank you for this dkms module. I got here from an issue you posted in the original module's repo.

I installed the module from here and I'm using it on Ubuntu 19.10, then I installed joycond. Joycond service is up and running, but for some reason it won't take control over the driver. If I connect a pro controller, I'm not required to press R+L to assign it as a controller and if I connect Joycons they are all assigned directly to singular joycons, not giving me a chance to join them with R+L.

Am I doing something wrong, or is this expected?

**Comment by nicman23** [comment]
i have not tested this with joycons (only the pro controller). i ll test it and report back

**Comment by DCNick3** [comment]
Can reproduce. `joycond` works with custom-compiled kernel, but not with `hid-nintendo-dkms` package from AUR.

**Comment by DanielOgorchock** [comment]
The issue with joycond is a hacky thing I have in the joycond udev rules. It checks for the rumble functionality being enabled for the input device to filter out the separate IMU evdev. I assume most people would want the rumble functionality enabled in the dkms module anyway. I'd recommend forcing CONFIG_NINTENDO_FF to enabled. Maybe just adding a `#define CONFIG_NINTENDO_FF 1` to the top of hid-nintendo.c in this repo would do the trick, since pretty much everyone will have the force feedback kconfigs enabled in their kernels anyway.

**Comment by joaorb64** [comment]
The #define did the trick! It's fully functional now. Also now Dolphin detects rumble for the controllers.

**Comment by nicman23** [comment]
oh nice, i ll commit it right now

**Comment by nicman23** [comment]
hmm for some reason, dolphin does not detect the rumble in my pro controller - but i do not have the joycond daemon installed

**Comment by DanielOgorchock** [comment]
joycond shouldn't impact pro controller rumble functionality. Does fftest work with the pro controller for you?

**Comment by joaorb64** [comment]
I tested using rumble on Dolphin and the intensity is too strong... to the point that I prefered turning it off.
I was also interested in using the gyro capabilities of the joycons, but from what I understood most emulators (Dolphin, Citra, Cemu) work with DSU Server Applications, which I guess should be developed as a separate application? Or is there already a way to use gyro input in emulators? (maybe going a bit off-topic here)

**Comment by DanielOgorchock** [comment]
You can lower the intensity of the rumble like shown below.
![Screenshot from 2020-04-06 12-20-47](https://user-images.githubusercontent.com/5153370/78586433-0e64aa00-7801-11ea-93de-89318ff2a6ed.png)

I just pushed a new patch to joycond that updates the udev rules to make the IMU accessible by non-root users. You can then configure dolphin to use the accel/gyro on its motion input tab as shown below. Note you have to right click on the inputs to select from the list. This was done with the pro controller, but it should be the same for the joy-cons (though I'm not sure if dolphin will associate both IMUs with the joycond virtual device).
![Screenshot from 2020-04-06 12-17-36](https://user-images.githubusercontent.com/5153370/78586231-c5145a80-7800-11ea-8234-0c73ec435065.png)

edit: You can use the left and right joy-con imu devices separately for the wii remote and nunchuck. Just select the IMU devices when right clicking on the motion input bindings.

**Comment by nicman23** [comment]
@DanielOgorchock updated the module to not check for the ff flag. also i had to uninstall joycond due to the /dev/input of both the controller and the gyro having too restrictive permissions (and i am not using joycons anyways).

E: i just read through your dolphin post, so the joycond permission is fixed ?

**Comment by DanielOgorchock** [comment]
joycond restricts the main input device's permissions until you "pair" the controller by pressing both triggers together (it will stop flashing the LEDs and restore permissions). The patch I just submitted fixes permissions for the IMU evdev.

edit: I also went ahead and removed joycond's udev rules' dependency on checking for the force feedback capability (it filters out the IMU based on the name now). This should avoid the problem associated with building hid-nintendo without force feedback support.

**Comment by nicman23** [comment]
@DanielOgorchock ah i see. also with the dkms module as is i am getting a lot of disconnects
```
[14173.733237] nintendo 0005:057E:2009.001C: controller MAC = 7C:BB:8A:F9:25:B1
[14173.839880] input: Nintendo Switch Pro Controller as /devices/pci0000:00/0000:00:01.3/0000:02:00.0/usb1/1-4/1-4.3/1-4.3:1.0/bluetooth/hci0/hci0:11/0005:057E:2009.001C/input/input69
[14173.840327] input: Nintendo Switch Pro Controller IMU as /devices/pci0000:00/0000:00:01.3/0000:02:00.0/usb1/1-4/1-4.3/1-4.3:1.0/bluetooth/hci0/hci0:11/0005:057E:2009.001C/input/input70
[14222.277068] nintendo 0005:057E:2009.001D: unknown main item tag 0x0
[14222.277171] nintendo 0005:057E:2009.001D: hidraw10: BLUETOOTH HID v80.01 Gamepad [Pro Controller] on 00:19:86:00:00:47
[14224.627054] nintendo 0005:057E:2009.001D: controller MAC = 7C:BB:8A:F9:25:B1
[14224.702560] input: Nintendo Switch Pro Controller as /devices/pci0000:00/0000:00:01.3/0000:02:00.0/usb1/1-4/1-4.3/1-4.3:1.0/bluetooth/hci0/hci0:11/0005:057E:2009.001D/input/input71
[14224.702775] input: Nintendo Switch Pro Controller IMU as /devices/pci0000:00/0000:00:01.3/0000:02:00.0/usb1/1-4/1-4.3/1-4.3:1.0/bluetooth/hci0/hci0:11/0005:057E:2009.001D/input/input72

```

but usb works as intended

**Comment by joaorb64** [comment]
I was messing up with motion input on Dolphin and was sad that I couldn't use motion in other emulators like Cemu, Citra, etc, so I researched for a bit and put this together: https://github.com/joaorb64/joycond-cemuhook

With this you can setup dual joycon buttons on Dolphin and have the motion input be automatically assigned without any extra configs, and also use the input for other emulators.
**Edit**: Now supports Switch Pro Controller and has an extra config for correct gyro input for wine applications

I also created this guide https://joaorb64.github.io/2020/04/08/using-nintendo-switch-controllers-on-linux.html that I intend to improve on soon with individual installing steps.
