### ISSUE TITLE
Error on Build

### ISSUE THREAD

**Issue by Mumrik93** [nicman23/dkms-hid-nintendo#14]
Been trying for about 40 min to install this but i keep getting the same error-message;

"Error! Could not find module source directory.
Directory: /usr/src/nintendo-1.0 does not exist."

I tried removing all the files and clone the git again, doing it all over, but i kept getting the same error again :( Being a noob I have to admit defeat and hope someone else knows what the issue might be caused by.

**Comment by joaorb64** [comment]
If you open `/usr/src/`, is there a `nintendo-x` directory there?
My guess is that the current version creates `nintendo-2.0` instead of `1.0`, so try changing the version number when running the commands.

**Comment by Mumrik93** [comment]
Gave that a try and it did indeed solve the problem, thank you!
