### ISSUE TITLE
JoyCons assigned automatically without waiting?

### ISSUE THREAD

**Issue by ademlabs** [nicman23/dkms-hid-nintendo#17]
I have two JoyCons that are paired but they are immediately assigned as individual controllers for Left and Right joycons. I can see them in the Game Controller app (KDE) and all buttons work normally. I was under the impression that the lights should be blinking and I had to use joycond to set up the modes? It looks like hid-nintendo is assigning the roles immediately.

**Comment by nicman23** [comment]
yeah that is how the driver works. you need joycond for merging
