### ISSUE TITLE
Issue with third party controller

### ISSUE THREAD

**Issue by DraconYale** [nicman23/dkms-hid-nintendo#19]
I'm using a TUTUO third party Pro Controller. When I connect it via USB the leds on the controller keeps blinking (as it is trying to connect) and `dmesg` prints this output:
https://gist.github.com/DraconYale/9b41db5134d50138a27a34c2c98b0c31
If I try to connect it via bluetooth it disconnects immediately.

Official Pro Controller works via USB and bluetooth and it is recognized correctly.

Distro: Manjaro Linux
Kernel Version: 5.8.11-1
I'm using the AUR package

**Comment by nicman23** [comment]
please report this to https://github.com/DanielOgorchock/linux
