### ISSUE TITLE
Gyro broken on latest commit when using cemuhook-joycond

### ISSUE THREAD

**Issue by Phantop** [nicman23/dkms-hid-nintendo#20]
Using an official Pro controller over USB on Solus 4.1 (which doesn't have DKMS so I'm using the Makefile as shown [here](https://github.com/Phantop/solus-stuff/blob/master/hid-nintendo/package.yml)) on kernel 5.6.19. 

When using Dolphin, the gyro-based pointer is completely broken on the latest commit. Commit 3fe4a5856999fed4d2cf8e9ff6553bbb69f3835c (aka version 2.0) does not have this issue.

**Comment by nicman23** [comment]
this is a downstream repo. for these kinds of issues please go to https://github.com/DanielOgorchock/linux
