### ISSUE TITLE
Tag 3.1

### ISSUE THREAD

**Issue by sugar700** [nicman23/dkms-hid-nintendo#30]
https://github.com/nicman23/dkms-hid-nintendo/commits/master bumped the version to 3.1, a tag for it would be appreciated for packaging this in nixpkgs, see https://github.com/NixOS/nixpkgs/pull/108348.

**Comment by nicman23** [comment]
done

**Comment by v1993** [comment]
README.md also needs to update version number, by the way. Sorry for forgetting that. :\
