### ISSUE TITLE
cant install

### ISSUE THREAD

**Issue by EuphonSol** [nicman23/dkms-hid-nintendo#37]
everytime i try to do "sudo dkms add  ."
it tells me: "sudo: dkms: command not found"
even after restarting my terminal
help please?

**Comment by shadowofdarkness** [comment]
Do you have dkms installed on your system?

Check you package management system for it.
One example to install it on distributions that use apt is.
sudo apt install dkms

**Comment by EuphonSol** [comment]
oh cool it worked :)
