### ISSUE TITLE
Unable to reconnect without completely unpairing again (syslog error message attached)

### ISSUE THREAD

**Issue by zinahe** [nicman23/dkms-hid-nintendo#39]
Hi, 

I was able to connect to Joy-Con (L) and use it for a few minutes on a Raspberry Pi 3. But after a few minutes, the connection is dropped and I'm unable to re-connect to it. I have to un-pair it completely and repeat the whole process. I am getting these errors in the kernel syslog
 
kernel: [xxxxx] nintendo 0005:057E:2006.0008: Failed to enable rumble; ret=-110
kernel: [xxxxx] nintendo 0005:057E:2006.0008: probe - fail = -110
kernel: [xxxxx] nintendo: probe of 0005:057E:2006.0008 failed with error -110
bluetoothd[xxxxx]: B8:8A:EC:A5:22:BF: error updating services: Input/output error (5)

Additional info

$ dkms status
nintendo, 3.1, 4.19.66-v7+, armv7l: installed

$ sudo bluetoothctl
[bluetooth]# info B8:8A:EC:A5:22:BF
Device B8:8A:EC:A5:22:BF (public)
        Name: Joy-Con (L)
        Alias: Joy-Con (L)
        Class: 0x00000508
        Icon: input-gaming
        Paired: yes
        Trusted: yes
        Blocked: no
        Connected: no
        LegacyPairing: no
        UUID: Service Discovery Serve.. (00001000-0000-1000-8000-00805f9b34fb)
        UUID: Human Interface Device... (00001124-0000-1000-8000-00805f9b34fb)
        UUID: PnP Information           (00001200-0000-1000-8000-00805f9b34fb)
        Modalias: usb:v057Ep2006d0001   

Any help is greatly appreciated.

**Comment by nicman23** [comment]
yeah i have that too but i think that it is a bluetooth userland thing and not releated to the module. i ll report it to the module developer - this is a downstream project.
