### ISSUE TITLE
rumble issues

### ISSUE THREAD

**Issue by RawPointer** [nicman23/dkms-hid-nintendo#40]
The driver does not seem to differentiate between lighter and more strong rumble, the controller just rumbles at max strength.
Games that allow disabling rumble can bypass the problem, but some others do not, so anytime the controller is supposed to rumble lightly it goes max speed and many games are nigh unplayable that way.
Fixing the rumble sensitivity problem or providing a way to disable rumble altogether would be a fine addition.

**Comment by nicman23** [comment]
please report this on

https://github.com/DanielOgorchock/linux
