### ISSUE TITLE
Switch pro controller doesn't work.

### ISSUE THREAD

**Issue by ghost** [nicman23/dkms-hid-nintendo#42]
I tested it with dolphin,when I try to calibrate the analog stick,then it doesn't work.

**Comment by nicman23** [comment]
can you please show a screenshot of the dolphin's controller setup

**Comment by ghost** [comment]
I installed a new system and tested it,now the problem is that my nintendo switch pro controller doesn't get registered at all,when I look up the controller devices with an emulator or whatever.
This is my system information:
![image](https://user-images.githubusercontent.com/68649672/122860244-ac1c9a00-d31d-11eb-9325-7ff1876f5333.png)

**Comment by ghost** [comment]
I use it via usb btw

**Comment by ghost** [comment]
I tried it with other applications,the controller doesn't get listed in them.

**Comment by ghost** [comment]
When I do `lsusb -v` in the terminal and search for "switch",then I get:
```
Bus 003 Device 005: ID 057e:2009 Nintendo Co., Ltd Switch Pro Controller
```
And also when steam isn't running and I connect my switch pro controller via usb and then press a button,then the leds blinking and then they are off after some seconds and nothing works.

**Comment by ghost** [comment]
I tested it,it only works with steam and cemu,and the other problem is that with those apps the blue home led is turned on,even though I use joycond-nicman23-git.

**Comment by ghost** [comment]
When I test my switch pro controller after opening cemu with a program called sc-controller,then it is completely buggy,I don't press anything,but the program thinks that I press those buttons:
![image](https://user-images.githubusercontent.com/68649672/123021681-d1201400-d3d4-11eb-9c1a-492b64e3c765.png)

**Comment by ghost** [comment]
I hope that you can help me fast,cause I just want to play secret of mana with my controller now.

**Comment by ghost** [comment]
I installed the linux-headers and now the controller itself works,but not for sc-controller.

**Comment by ghost** [comment]
And the home led still glows blue when I start some programs like cemu or ppsspp.

**Comment by ghost** [comment]
I will close this issue and make two seperate ones for each of the issues.
