### ISSUE TITLE
Sometimes it showing the player 2 or 3 or 4 leds instead of just the player 1 led

### ISSUE THREAD

**Issue by ghost** [nicman23/dkms-hid-nintendo#43]
The green led buttons annoy me,I want that they are turned off.
And if that doesn't work,I want that only the player 1 led gets used.

**Comment by nicman23** [comment]
install joycond

**Comment by ghost** [comment]
I already installed [this package](https://aur.archlinux.org/packages/joycond-nicman23-git/),so how can i select that the green led's aren't on?

**Comment by nicman23** [comment]
oh sorry that is just for making it to be player 1 2 3 4 (when you connect multiple controllers)

if you really are that bothered with it i can see if i can get you a patch when i got some time.

**Comment by ghost** [comment]
But sometimes the player 2 led is blinking even though I only connected one controller,is that also intended?

**Comment by nicman23** [comment]
nothing should be blinking after initial connect

can you send a video with that?

**Comment by ghost** [comment]
I don't have a phone or cam,I can't make a video of that.
I don't mean that it is blinking after connecting,I mean that it is just green,but not only the player 1 led,but sometimes the player 2 led.

**Comment by ghost** [comment]
sometimes the 2 player leds or 3 player leds or 4 player leds are showing up instead of just the 1 player led even though I only have one controller connected.
