### ISSUE TITLE
The Home button of the Nintendo switch pro controller glows blue even though I have joycond-nicman23-git installed

### ISSUE THREAD

**Issue by ghost** [nicman23/dkms-hid-nintendo#44]
I installed joycond-nicman23-git,but when I open some programs (for example cemu and ppsspp),then the button glows blue.

**Comment by ghost** [comment]
I have to go to the steam settings and turn the led on and off so that it is off again.
But it is annoying to do that every time.

**Comment by ghost** [comment]
I use it via usb btw.

**Comment by nicman23** [comment]
works for me. the issue is steam and something on your install that allows it to access the controller regardless of the changes i have made in the my joycond fork
