### ISSUE TITLE
My switch pro controller doesn't work with sc-controller

### ISSUE THREAD

**Issue by ghost** [nicman23/dkms-hid-nintendo#45]
[sc-controller](https://github.com/kozec/sc-controller) is a program that emulates xbox360 input for controllers that aren't xbox360.
I want to use that for my switch pro controller cause many games only work with the xbox360 controller.
The problem is that I just can't add my controller,it doesn't show up:
![image](https://user-images.githubusercontent.com/68649672/123218102-9947c800-d4cb-11eb-93cb-908af0901744.png)
It is not a sc-controller problem,cause that supports hid devices.
I also checked,the switch controller is connected via usb and works with things like emulators.

**Comment by ghost** [comment]
I use it via usb by the way.

**Comment by nicman23** [comment]
https://github.com/DanielOgorchock/linux
