### ISSUE TITLE
Error! Arguments <module> and <module-version> are not specified.

### ISSUE THREAD

**Issue by GitEz-code** [nicman23/dkms-hid-nintendo#52]
i tried to build hid-nintendo, when i enter `sudo dkms add .` it give me this error: 
```
Error! Arguments <module> and <module-version> are not specified.
Usage: add <module>/<module-version> or
       add -m <module>/<module-version> or
       add -m <module> -v <module-version>
```
i'm on Manjaro btw

**Comment by Sanaki** [comment]
You're entering this from the directory containing the dkms.conf?

**Comment by GitEz-code** [comment]
Yes I was, but I finded a workaround, I just copied the folder in /usr/src, then I just followed the instruction and it work perfectly. (I'm sorry for my really bad English it's not my mother tongue)
