### ISSUE TITLE
[REQUEST] vice versa feature

### ISSUE THREAD

**Issue by z0rti** [nicman23/dkms-hid-nintendo#54]
I don't know where else to request this so i'll try it here :-)

How about a feature that connects to the switch, pretends to be a switch controller, but in fact
it is some other controller that is connected to a e.g. notebook, or raspberry pi

So e.g. XBoX controller connects via bt and or usb to notebook/pi, this driver would connect to a switch, presents this controller as original switch controller.

Could be a keyboard too, so we would be able to play switch with wasd :-)

It's probably not the goal of hid-nintendo, but anyway...

**Comment by nicman23** [comment]
i think hekate does that
