### ISSUE TITLE
user calibration support and bluetooth reliability improvement

### ISSUE THREAD

**Issue by DanielOgorchock** [nicman23/dkms-hid-nintendo#6]
I added these two patches:
https://github.com/DanielOgorchock/linux/commit/660cb228f829df1cdeb91bd9bdec48e1d392cfbf
https://github.com/DanielOgorchock/linux/commit/1c27248badf98c1eebbd7eed098e483d2d471ce3

The first adds support for preferring the joystick user calibration if present over the factory calibration. The second changes the driver's behavior to only send the rumble subcommands when the amplitude isn't zero. This seems to make the connectivity far more reliable for me, but it would be good to get more people testing with it.

Also this change is minor, but it fixes the way userspace sees the battery power supply in some cases:
https://github.com/DanielOgorchock/linux/commit/98b2874cfe46f8bbade2ccdc74d33379b0dcd9b2

**Comment by nicman23** [comment]
errm i guess mentioning `to close #6` in a git commit auto closes the issue.... anyhow, connection seems a lot better, i ll test it a bit more and probably make a 1.1 tag of it. thanks for your work
