### ISSUE TITLE
This version vs kernel version?

### ISSUE THREAD

**Issue by z0rti** [nicman23/dkms-hid-nintendo#61]
Not a bug but (important) question:

How do i see which version is currently used by the OS? (3.1? 3.2?)
Which version of hid-nintendo is in which kernel right now?
Do i need this dkms when i'm using kernel 5.15? 5.17 6.x?

**Comment by nicman23** [comment]
please use the kernel version. this repo was from a time that the module was not mainlined.

on 5.15 you can use dkms to remove it and then run depmod -a
