### ISSUE TITLE
How to remove?

### ISSUE THREAD

**Issue by Anonymous941** [nicman23/dkms-hid-nintendo#63]
How do I uninstall this?  It's making it impossible to use any controllers ever since I installed it and they were working fine before.  It doesn't show up on my `apt` packages.

**Comment by Anonymous941** [comment]
Why did you close this?

**Comment by nfp0** [comment]
@Anonymous941 That question is unrelated to this project.

You've gotta google how to remove or uninstall DKMS modules in Linux, or in your distro specifically.
You probably have not installed this through apt.

**Comment by Anonymous941** [comment]
@nfp0 Okay, thank you, I've removed the DKMS module.
