### ISSUE TITLE
after installation no controllers work in games

### ISSUE THREAD

**Issue by greasysock** [nicman23/dkms-hid-nintendo#9]
After I installed this no controllers would work. I could see ps4/xbox one/switch controllers in jstest and they worked fine but they would not appear in any games. After I installed joycond the switch controllers began to work but only those. After uninstalling this and joycond no controllers are showing up. I am pretty dumbfounded at this. What other steps could I take to fix this?

I am running Arch Linux and installed the git versions of both dkms-hid-nintendo and joycond directly and not through AUR.

For xbox one controllers I am using xow with a microsoft adapter, and the ps4 controller I am connecting via bluetooth with no special drivers.

Overall, I am pretty excited for this. I have been waiting for this kind of compatibility since launch.

**Comment by nicman23** [comment]
if you are not using joycons, there is no need for joycond. nevertheless, this is a joycond issue (that is no managed by me or this repo)
